services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_template
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
